<a href="https://colab.research.google.com/github/mrrahim1111/xhudhjkvd/blob/main/Backend.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================================
# BACKEND CELL 1 — ROTATION ENGINE
# ============================================

import numpy as np

# -----------------------------
# INPUTS
# -----------------------------

x = 100
y = 50

angle = 90
direction = 1      # 1 = CCW, -1 = CW


# -----------------------------
# ROTATION MATRIX
# -----------------------------

def rotation_matrix(angle, direction=1):

    theta = np.radians(direction * angle)

    Q = np.array([
        [np.cos(theta), -np.sin(theta)],
        [np.sin(theta),  np.cos(theta)]
    ])

    return Q


# -----------------------------
# TRANSFORMATION
# -----------------------------

P = np.array([x, y], dtype=float)

Q = rotation_matrix(angle, direction)

P_rotated = Q @ P


# -----------------------------
# DISPLAY
# -----------------------------

print("SCREEN ROTATION BACKEND")
print("=" * 35)

print(f"Original Point : {P}")
print(f"Rotation Angle : {angle}°")

print("\nRotation Matrix Q:")
print(np.round(Q, 4))

print("\nRotated Point P' = QP:")
print(np.round(P_rotated, 4))

SCREEN ROTATION BACKEND
Original Point : [100.  50.]
Rotation Angle : 90°

Rotation Matrix Q:
[[ 0. -1.]
 [ 1.  0.]]

Rotated Point P' = QP:
[-50. 100.]


In [2]:
# ============================================
# BACKEND CELL 2 — MATHEMATICAL VERIFICATION
# ============================================

# Orthogonality
QTQ = Q.T @ Q
orthogonal = np.allclose(QTQ, np.eye(2))


# Determinant
det_Q = np.linalg.det(Q)


# Distance preservation
original_distance = np.linalg.norm(P)
rotated_distance = np.linalg.norm(P_rotated)

distance_preserved = np.isclose(
    original_distance,
    rotated_distance
)


# Quadratic form
original_quadratic = P.T @ P
rotated_quadratic = P_rotated.T @ P_rotated

quadratic_invariant = np.isclose(
    original_quadratic,
    rotated_quadratic
)


# Double rotation
Q2 = Q @ Q
P2 = Q @ P_rotated


# -----------------------------
# RESULTS
# -----------------------------

print("MATHEMATICAL VERIFICATION")
print("=" * 35)

print("\nQᵀQ:")
print(np.round(QTQ, 4))

print("\nOrthogonal:", orthogonal)

print("\ndet(Q):", round(det_Q, 4))

print("\nOriginal Distance:",
      round(original_distance, 4))

print("Rotated Distance:",
      round(rotated_distance, 4))

print("Distance Preserved:",
      distance_preserved)

print("\nPᵀP:",
      round(original_quadratic, 4))

print("P'ᵀP':",
      round(rotated_quadratic, 4))

print("Quadratic Form Invariant:",
      quadratic_invariant)

print("\nAfter Two Rotations:")
print(np.round(P2, 4))

print("\nQ²:")
print(np.round(Q2, 4))

if np.isclose(abs(angle), 90):
    print("\nTwo 90° rotations = 180° rotation")

MATHEMATICAL VERIFICATION

QᵀQ:
[[1. 0.]
 [0. 1.]]

Orthogonal: True

det(Q): 1.0

Original Distance: 111.8034
Rotated Distance: 111.8034
Distance Preserved: True

PᵀP: 12500.0
P'ᵀP': 12500.0
Quadratic Form Invariant: True

After Two Rotations:
[-100.  -50.]

Q²:
[[-1. -0.]
 [ 0. -1.]]

Two 90° rotations = 180° rotation
